title = "A list of rules for processing Apple Transactions."

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Banana Republic"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Clothing"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Apple Services"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Subscription"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Phillips 66"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Auto:Gas"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Ridge Wallet"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Gear"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Martin's Supermarket"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Groceries"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Apple Cash Payment"

[[rules.apply]]
op = "assign"
column = "From"
b = "Income:Apple Cash"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Hulu"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Entertainment"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Trade Coffee CO"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Groceries"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Beacon Med"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Medical:Body"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "South Bend Clinic"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Medical:Body"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "WMMH"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Entertainment:Self"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Account Ending In 8785"

[[rules.apply]]
op = "assign"
column = "From"
b = "Assets:1st Source:Checking"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "bookshop.org"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Study"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Patreon"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Entertainment"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Monthly Installments"

[[rules.apply]]
op = "assign"
column = "From"
b = "Liabilities:Apple:Installments"

[[rules]]
[[rules.select]]
op = "contains"
column = "Category"
a = "None"
b = "Tolls"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Auto:Tolls"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Kobo"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Entertainment:Reading"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Vtsup.com"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Entertainment:Self"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "City Of South Bend"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Utilities"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Andrasi"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Home:Cleaning"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Parlevel Texas"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Restaurants"

[[rules]]
[[rules.select]]
op = "contains"
column = "Merchant"
a = "None"
b = "Gannett Newsprpr"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Utilities"

[[rules]]
[[rules.select]]
op = "contains"
column = "Description"
a = "None"
b = "ABEBOOKS"

[[rules.apply]]
op = "assign"
column = "From"
b = "Expenses:Study"
